/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Scientific_Calculator;

/**
 *
 * @author USER
 */
public class Scientific_Calculator extends javax.swing.JFrame {
    double firstnum;
    double secondnum;
    double result;
    int n;
    String operations;
    private Object math;

    /**
     * Creates new form Scientific_Calculator
     */
    public Scientific_Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtDisplay = new javax.swing.JTextField();
        jClear = new javax.swing.JButton();
        jSqrt = new javax.swing.JButton();
        jBackspace = new javax.swing.JButton();
        jAdd = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        jMul = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        j1 = new javax.swing.JButton();
        jDiv = new javax.swing.JButton();
        jDot = new javax.swing.JButton();
        jPlusMinus = new javax.swing.JButton();
        j0 = new javax.swing.JButton();
        jEquals = new javax.swing.JButton();
        j8 = new javax.swing.JButton();
        j9 = new javax.swing.JButton();
        j7 = new javax.swing.JButton();
        jSub = new javax.swing.JButton();
        jSin = new javax.swing.JButton();
        jHexa = new javax.swing.JButton();
        jBinary = new javax.swing.JButton();
        jSinh = new javax.swing.JButton();
        jTan = new javax.swing.JButton();
        jCosh = new javax.swing.JButton();
        jLog = new javax.swing.JButton();
        jXY = new javax.swing.JButton();
        jTanh = new javax.swing.JButton();
        jX3 = new javax.swing.JButton();
        jDiv1 = new javax.swing.JButton();
        jSub3 = new javax.swing.JButton();
        jX2 = new javax.swing.JButton();
        jCos = new javax.swing.JButton();
        jPie = new javax.swing.JButton();
        jOctal = new javax.swing.JButton();
        jExp = new javax.swing.JButton();
        jlnx = new javax.swing.JButton();
        jModulus = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        jtxtDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDisplayKeyTyped(evt);
            }
        });

        jClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jClear.setText("© ");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });

        jSqrt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSqrt.setText("√ ");
        jSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSqrtActionPerformed(evt);
            }
        });

        jBackspace.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jBackspace.setText("←");
        jBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackspaceActionPerformed(evt);
            }
        });

        jAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jAdd.setText("+");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        j5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j5.setText("5");
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });

        j6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j6.setText("6");
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });

        j4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j4.setText("4");
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });

        jMul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMul.setText("*");
        jMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMulActionPerformed(evt);
            }
        });

        j2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j2.setText("2");
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });

        j3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j3.setText("3");
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });

        j1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j1.setText("1");
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        jDiv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDiv.setText("/");
        jDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDivActionPerformed(evt);
            }
        });

        jDot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDot.setText(".");
        jDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDotActionPerformed(evt);
            }
        });

        jPlusMinus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPlusMinus.setText("±");
        jPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlusMinusActionPerformed(evt);
            }
        });

        j0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j0.setText("0");
        j0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j0ActionPerformed(evt);
            }
        });

        jEquals.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEquals.setText("=");
        jEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEqualsActionPerformed(evt);
            }
        });

        j8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j8.setText("8");
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ActionPerformed(evt);
            }
        });

        j9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j9.setText("9");
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ActionPerformed(evt);
            }
        });

        j7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j7.setText("7");
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ActionPerformed(evt);
            }
        });

        jSub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSub.setText("-");
        jSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubActionPerformed(evt);
            }
        });

        jSin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSin.setText("Sin");
        jSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSinActionPerformed(evt);
            }
        });

        jHexa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jHexa.setText("Hex");
        jHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHexaActionPerformed(evt);
            }
        });

        jBinary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBinary.setText("Bin");
        jBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinaryActionPerformed(evt);
            }
        });

        jSinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSinh.setText("Sinh");
        jSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSinhActionPerformed(evt);
            }
        });

        jTan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTan.setText("tan");
        jTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTanActionPerformed(evt);
            }
        });

        jCosh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCosh.setText("Cosh");
        jCosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCoshActionPerformed(evt);
            }
        });

        jLog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLog.setText("Log");
        jLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogActionPerformed(evt);
            }
        });

        jXY.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXY.setText("x^y");
        jXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXYActionPerformed(evt);
            }
        });

        jTanh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTanh.setText("tanh");
        jTanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTanhActionPerformed(evt);
            }
        });

        jX3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jX3.setText("x^3");
        jX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jX3ActionPerformed(evt);
            }
        });

        jDiv1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDiv1.setText("Cbr");
        jDiv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDiv1ActionPerformed(evt);
            }
        });

        jSub3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSub3.setText("Round");
        jSub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSub3ActionPerformed(evt);
            }
        });

        jX2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jX2.setText("x^2");
        jX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jX2ActionPerformed(evt);
            }
        });

        jCos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCos.setText("Cos");
        jCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCosActionPerformed(evt);
            }
        });

        jPie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPie.setText("π");
        jPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPieActionPerformed(evt);
            }
        });

        jOctal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jOctal.setText("Octal");
        jOctal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOctalActionPerformed(evt);
            }
        });

        jExp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jExp.setText("Exp");
        jExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExpActionPerformed(evt);
            }
        });

        jlnx.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlnx.setText("lnx");
        jlnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlnxActionPerformed(evt);
            }
        });

        jModulus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jModulus.setText("%");
        jModulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModulusActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Scientific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j0, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDot, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(j6, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                            .addComponent(j3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jMul, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(2, 2, 2))
                                        .addComponent(jDiv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jX2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDiv1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSub3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jX3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jOctal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jXY, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jExp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLog, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jModulus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPie, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlnx, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBackspace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSub, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPie, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlnx, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jModulus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLog, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jMul, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jXY, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTan, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jExp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jX2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDiv1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSub3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jX3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDot, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOctal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      this.setResizable(true);
      this.setSize(350, 550);
    }//GEN-LAST:event_formWindowActivated

    private void j9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ActionPerformed
        String iNum = jtxtDisplay.getText() + j9.getText();
        jtxtDisplay.setText(iNum);
// TODO add your handling code here:
    }//GEN-LAST:event_j9ActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void j7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ActionPerformed
       String iNum = jtxtDisplay.getText() + j7.getText();
        jtxtDisplay.setText(iNum);

// TODO add your handling code here:
    }//GEN-LAST:event_j7ActionPerformed

    private void j8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ActionPerformed
        String iNum = jtxtDisplay.getText() + j8.getText();
        jtxtDisplay.setText(iNum);

// TODO add your handling code here:
    }//GEN-LAST:event_j8ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
       String iNum = jtxtDisplay.getText() + j4.getText();
        jtxtDisplay.setText(iNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_j4ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
String iNum = jtxtDisplay.getText() + j5.getText();
        jtxtDisplay.setText(iNum);        
// TODO add your handling code here:
    }//GEN-LAST:event_j5ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
    String iNum = jtxtDisplay.getText() + j6.getText();
        jtxtDisplay.setText(iNum);
        // TODO add your handling code here:
    }//GEN-LAST:event_j6ActionPerformed

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        String iNum = jtxtDisplay.getText() + j1.getText();
        jtxtDisplay.setText(iNum);
// TODO add your handling code here:
    }//GEN-LAST:event_j1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        String iNum = jtxtDisplay.getText() + j2.getText();
        jtxtDisplay.setText(iNum);
// TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        String iNum = jtxtDisplay.getText() + j3.getText();
        jtxtDisplay.setText(iNum);// TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    private void j0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j0ActionPerformed
        String iNum = jtxtDisplay.getText() + j0.getText();
        jtxtDisplay.setText(iNum);
// TODO add your handling code here:
    }//GEN-LAST:event_j0ActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        jtxtDisplay.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jClearActionPerformed

    private void jBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackspaceActionPerformed
    String bsp = null;
    
    if(jtxtDisplay.getText().length() > 0)
    {
        StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
        strB.deleteCharAt(jtxtDisplay.getText().length() - 1);
        bsp = strB.toString();
        jtxtDisplay.setText(bsp);
    }
// TODO add your handling code here:
    }//GEN-LAST:event_jBackspaceActionPerformed

    private void jDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDotActionPerformed
    if(!jtxtDisplay.getText().contains(".")) ;
    {
        jtxtDisplay.setText(jtxtDisplay.getText() + jDot.getText());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jDotActionPerformed

    private void jPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlusMinusActionPerformed
       double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
       ops =  ops = ops *(-1);
       jtxtDisplay.setText(String.valueOf(ops));
               // TODO add your handling code here:
    }//GEN-LAST:event_jPlusMinusActionPerformed

    private void jSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSqrtActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
       ops = Math.sqrt(ops);
       jtxtDisplay.setText(String.valueOf(ops));
// TODO add your handling code here:
    }//GEN-LAST:event_jSqrtActionPerformed

    private void jLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogActionPerformed
         double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
       ops = Math.log(ops);
       jtxtDisplay.setText(String.valueOf(ops));
// TODO add your handling code here:
    }//GEN-LAST:event_jLogActionPerformed

    private void jSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSinActionPerformed
         double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
         ops=Math.toRadians(ops);
       ops = Math.sin(ops);
       jtxtDisplay.setText(String.valueOf(ops));
// TODO add your handling code here:
    }//GEN-LAST:event_jSinActionPerformed

    private void jSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSinhActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops=Math.toRadians(ops);
       ops = Math.sinh(ops);
       jtxtDisplay.setText(String.valueOf(ops));
// TODO add your handling code here:
    }//GEN-LAST:event_jSinhActionPerformed

    private void jCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCosActionPerformed
       double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
       ops=Math.toRadians(ops);
       ops = Math.cos(ops);
       jtxtDisplay.setText(String.valueOf(ops)); 
    }//GEN-LAST:event_jCosActionPerformed

    private void jCoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCoshActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops=Math.toRadians(ops);
       ops = Math.cosh(ops);
       jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jCoshActionPerformed

    private void jTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTanActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops=Math.toRadians(ops);
       ops = Math.tan(ops);
       jtxtDisplay.setText(String.valueOf(ops));
// TODO add your handling code here:
    }//GEN-LAST:event_jTanActionPerformed

    private void jTanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTanhActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops=Math.toRadians(ops);
       ops = Math.tanh(ops);
       jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jTanhActionPerformed

    private void jDiv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDiv1ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
       ops = Math.cbrt(ops);
       jtxtDisplay.setText(String.valueOf(ops));
// TODO add your handling code here:
    }//GEN-LAST:event_jDiv1ActionPerformed

    private void jSub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSub3ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
       ops = Math.round(ops);
       jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jSub3ActionPerformed

    private void jPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPieActionPerformed
        double ops;
    ops = Math.PI;
    jtxtDisplay.setText(String.valueOf(ops));

    }//GEN-LAST:event_jPieActionPerformed

    private void jXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXYActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
       ops = Math.pow(ops,ops);
       jtxtDisplay.setText(String.valueOf(ops));
// TODO add your handling code here:
    }//GEN-LAST:event_jXYActionPerformed

    private void jX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jX2ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
       ops = (ops * ops);
       jtxtDisplay.setText(String.valueOf(ops));
       // TODO add your handling code here:
    }//GEN-LAST:event_jX2ActionPerformed

    private void jX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jX3ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
       ops = (ops * ops *ops);
       jtxtDisplay.setText(String.valueOf(ops));
// TODO add your handling code here:
    }//GEN-LAST:event_jX3ActionPerformed

    private void jBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinaryActionPerformed
    int a = Integer.parseInt(jtxtDisplay.getText());//Binary
   jtxtDisplay.setText(Integer.toString(a,2));
// TODO add your handling code here:
    }//GEN-LAST:event_jBinaryActionPerformed

    private void jHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHexaActionPerformed
        int a = Integer.parseInt(jtxtDisplay.getText());//Hexadecimal
   jtxtDisplay.setText(Integer.toString(a,16));
// TODO add your handling code here:
    }//GEN-LAST:event_jHexaActionPerformed

    private void jtxtDisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDisplayKeyTyped
      // char c =evt.getKeyChar();
     //  if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)))
      // {
       //    getToolkit().beep();
        //   evt.consume();
       // }

// TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayKeyTyped

    private void jEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEqualsActionPerformed
    String answer;
    secondnum = Double.parseDouble(jtxtDisplay.getText());
    if(operations == "+")
    {
        result = firstnum + secondnum;
        answer = String.format("%.2f",result);
        jtxtDisplay.setText(answer);
    }
    else if(operations == "-")
    {
         result = firstnum - secondnum;
        answer = String.format("%.2f",result);
        jtxtDisplay.setText(answer);
    }
     else if(operations == "*")
    {
         result = firstnum * secondnum;
        answer = String.format("%.2f",result);
        jtxtDisplay.setText(answer);
    }
     else if(operations == "/")
    {
         result = firstnum / secondnum;
        answer = String.format("%.2f",result);
        jtxtDisplay.setText(answer);
    }
     else if(operations == "%")
    {
         result = firstnum % secondnum;
        answer = String.format("%.2f",result);
        jtxtDisplay.setText(answer);
    }
    
// TODO add your handling code here:
    }//GEN-LAST:event_jEqualsActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("+");
// TODO add your handling code here:
    }//GEN-LAST:event_jAddActionPerformed

    private void jSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubActionPerformed
         firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("-");
// TODO add your handling code here:
    }//GEN-LAST:event_jSubActionPerformed

    private void jMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMulActionPerformed
         firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("*");// TODO add your handling code here:
    }//GEN-LAST:event_jMulActionPerformed

    private void jDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDivActionPerformed
         firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("/");// TODO add your handling code here:
    }//GEN-LAST:event_jDivActionPerformed

    private void jOctalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOctalActionPerformed
        int a = Integer.parseInt(jtxtDisplay.getText());//Octal
   jtxtDisplay.setText(Integer.toString(a,8));
// TODO add your handling code here:
    }//GEN-LAST:event_jOctalActionPerformed

    private void jlnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlnxActionPerformed
          double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
       ops = Math.log10(ops);
       jtxtDisplay.setText(String.valueOf(ops));
// TODO add your handling code here:
    }//GEN-LAST:event_jlnxActionPerformed

    private void jModulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModulusActionPerformed
         firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations=("%");
// TODO add your handling code here:
    }//GEN-LAST:event_jModulusActionPerformed

    private void jExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExpActionPerformed
          double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
       ops = Math.exp(ops);
       jtxtDisplay.setText(String.valueOf(ops));
       // TODO add your handling code here:
    }//GEN-LAST:event_jExpActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setResizable(true);
        this.setSize(700, 550);
        jtxtDisplay.setSize(580, 50);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setResizable(true);
        this.setSize(350, 550);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scientific_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scientific_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scientific_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scientific_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scientific_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j0;
    private javax.swing.JButton j1;
    private javax.swing.JButton j2;
    private javax.swing.JButton j3;
    private javax.swing.JButton j4;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JButton j9;
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jBackspace;
    private javax.swing.JButton jBinary;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jClear;
    private javax.swing.JButton jCos;
    private javax.swing.JButton jCosh;
    private javax.swing.JButton jDiv;
    private javax.swing.JButton jDiv1;
    private javax.swing.JButton jDot;
    private javax.swing.JButton jEquals;
    private javax.swing.JButton jExp;
    private javax.swing.JButton jHexa;
    private javax.swing.JButton jLog;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JButton jModulus;
    private javax.swing.JButton jMul;
    private javax.swing.JButton jOctal;
    private javax.swing.JButton jPie;
    private javax.swing.JButton jPlusMinus;
    private javax.swing.JButton jSin;
    private javax.swing.JButton jSinh;
    private javax.swing.JButton jSqrt;
    private javax.swing.JButton jSub;
    private javax.swing.JButton jSub3;
    private javax.swing.JButton jTan;
    private javax.swing.JButton jTanh;
    private javax.swing.JButton jX2;
    private javax.swing.JButton jX3;
    private javax.swing.JButton jXY;
    private javax.swing.JButton jlnx;
    private javax.swing.JTextField jtxtDisplay;
    // End of variables declaration//GEN-END:variables
}
